#!/usr/bin/env python3

import os
import subprocess
import sys
from urllib.request import urlopen

def get_programs_list(repo, filename):
    url = f"https://raw.githubusercontent.com/{repo}/main/{filename}"
    try:
        with urlopen(url) as response:
            content = response.read().decode('utf-8').strip()
            programs = [line.strip() for line in content.split('\n')]
            return programs
    except Exception as e:
        print(f"No se pudo obtener la lista de programas desde {url}: {e}")
        return []

def install(programs):
    installed = []
    not_installed = []
    total_programs = len(programs)
    for i, program in enumerate(programs, start=1):
        print(f"Instalando {program} ({i}/{total_programs})...")
        result = subprocess.run(['sudo', 'DEBIAN_FRONTEND=noninteractive', 'apt', 'install', '-y', program], capture_output=True)
        if result.returncode == 0:
            installed.append(program)
        else:
            not_installed.append(program)
        clear_screen()
    return installed, not_installed

def remove(programs):
    uninstalled = []
    not_uninstalled = []
    total_programs = len(programs)
    for i, program in enumerate(programs, start=1):
        print(f"Removiendo {program} ({i}/{total_programs})...")
        result = subprocess.run(['sudo', 'DEBIAN_FRONTEND=noninteractive', 'apt', 'remove', '-y', program], capture_output=True)
        if result.returncode == 0:
            uninstalled.append(program)
        else:
            not_uninstalled.append(program)
        clear_screen()
    return uninstalled, not_uninstalled

def clear_screen():
    os.system('clear' if os.name == 'posix' else 'cls')

def main():
    repo = 'ManuMeisen/Meisen'  # Reemplaza con tu usuario y nombre del repositorio

    if len(sys.argv) < 3:
        print("Uso: python programa.py <install/remove> <lista1> <lista2> ...")
        return

    action = sys.argv[1]
    lists_to_install = sys.argv[2:]

    if action == 'install':
        installed = []
        not_installed = []
        for lista in lists_to_install:
            programs = get_programs_list(repo, lista)
            if programs:
                installed_list, not_installed_list = install(programs)
                installed.extend(installed_list)
                not_installed.extend(not_installed_list)
            else:
                print(f"No se encontró la lista '{lista}' en el repositorio.")
        
        print("Programas instalados:")
        for program in installed:
            print("-", program)
        print("Programas no instalados:")
        for program in not_installed:
            print("-", program)
        
    elif action == 'remove':
        uninstalled = []
        not_uninstalled = []
        for lista in lists_to_install:
            programs = get_programs_list(repo, lista)
            if programs:
                uninstalled_list, not_uninstalled_list = remove(programs)
                uninstalled.extend(uninstalled_list)
                not_uninstalled.extend(not_uninstalled_list)
            else:
                print(f"No se encontró la lista '{lista}' en el repositorio.")
        
        print("Programas desinstalados:")
        for program in uninstalled:
            print("-", program)
        print("Programas no desinstalados:")
        for program in not_uninstalled:
            print("-", program)
    else:
        print("Acción no reconocida. Use 'install' o 'remove'.")

if __name__ == "__main__":
    main()
